# docker-compose.yml

version: "3"
services:
  app:
    build: ./exptnode
    container_name: exptnode
    hostname: exptnode
    depends_on:
      - postgres
    ports:
      - "3030:3030"
  postgres:
    image: postgres:13
    container_name: exptdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=expt
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
  nginx:
    image: nginx:latest
    container_name: exptnginx
    hostname: expt
    build: ./exptnginx
    ports:
      - "80:80"
volumes:
  pgdata:
